VegaIT.TimeSheet.Web/Controllers/TimeSheetsController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using VegaIT.TimeSheet.Business.Contracts;
using VegaIT.TimeSheet.Business.Contracts.Exceptions;
using VegaIT.TimeSheet.Common;
using VegaIT.TimeSheet.DAL.Contracts.Entities;
using VegaIT.TimeSheet.DAL.Contracts.Repositories;
using VegaIT.TimeSheet.Web.Helpers;
using VegaIT.TimeSheet.Web.Models;

namespace VegaIT.TimeSheet.Web.Controllers
{
    [Error]
    public class TimeSheetsController : Controller
    {
        private readonly ITimeSheetManager timeSheetManager;
        private readonly ITeamMemberManager teamMemberManager;
        private readonly IClientManager clientManager;
        private readonly IProjectManager projectManager;
        private readonly ICategoryRepository categoryRepository;
        private readonly IProjectCategoryRepository projectCategoryRepository;

        public TimeSheetsController(ITimeSheetManager timeSheetManager, IClientManager clientManager, IProjectManager projectManager,
                                    ICategoryRepository categoryRepository, IProjectCategoryRepository projectCategoryRepository, ITeamMemberManager teamMemberManager)
        {
            this.timeSheetManager = timeSheetManager;
            this.clientManager = clientManager;
            this.projectManager = projectManager;
            this.categoryRepository = categoryRepository;
            this.projectCategoryRepository = projectCategoryRepository;
            this.teamMemberManager = teamMemberManager;
        }

        [Error]
        // GET: TimeSheets
        public ActionResult Index(int year, int month, int day)
        {
            try
            {
                DateTime currentDate = new DateTime(year, month, day);
                List<Tuple<int, int, int, string, string>> DaysOfWeek = new List<Tuple<int, int, int, string, string>>();
                decimal dayTotalTime = 0;

                var timeSheets = this.timeSheetManager.GetAll().Where(ts => ts.Date.Equals(currentDate));
                var clients = this.clientManager.GetAll();
                var projects = this.projectManager.GetAll();
                var categories = this.categoryRepository.GetAll();
                var projectCategories = this.projectCategoryRepository.GetAll();

                if (currentDate.DayOfWeek.Equals(DayOfWeek.Monday))
                {
                    CurrentDay(year, month, day, ref DaysOfWeek);
                    DaysAfter(year, month, day, 6, ref DaysOfWeek);
                }
                else if (currentDate.DayOfWeek.Equals(DayOfWeek.Tuesday))
                {
                    DaysBefore(year, month, day, 1, ref DaysOfWeek);
                    CurrentDay(year, month, day, ref DaysOfWeek);
                    DaysAfter(year, month, day, 5, ref DaysOfWeek);
                }
                else if (currentDate.DayOfWeek.Equals(DayOfWeek.Wednesday))
                {
                    DaysBefore(year, month, day, 2, ref DaysOfWeek);
                    CurrentDay(year, month, day, ref DaysOfWeek);
                    DaysAfter(year, month, day, 4, ref DaysOfWeek);
                }
                else if (currentDate.DayOfWeek.Equals(DayOfWeek.Thursday))
                {
                    DaysBefore(year, month, day, 3, ref DaysOfWeek);
                    CurrentDay(year, month, day, ref DaysOfWeek);
                    DaysAfter(year, month, day, 3, ref DaysOfWeek);
                }
                else if (currentDate.DayOfWeek.Equals(DayOfWeek.Friday))
                {
                    DaysBefore(year, month, day, 4, ref DaysOfWeek);
                    CurrentDay(year, month, day, ref DaysOfWeek);
                    DaysAfter(year, month, day, 2, ref DaysOfWeek);
                }
                else if (currentDate.DayOfWeek.Equals(DayOfWeek.Saturday))
                {
                    DaysBefore(year, month, day, 5, ref DaysOfWeek);
                    CurrentDay(year, month, day, ref DaysOfWeek);
                    DaysAfter(year, month, day, 1, ref DaysOfWeek);
                }
                else
                {
                    DaysBefore(year, month, day, 6, ref DaysOfWeek);
                    CurrentDay(year, month, day, ref DaysOfWeek);
                }

                if (timeSheets != null)
                {
                    foreach (DAL.Contracts.Entities.TimeSheet ts in timeSheets)
                    {
                        dayTotalTime += ts.Time;
                    }
                }

                TimeSheetDetailViewModel timeSheetsDetailViewModel = new TimeSheetDetailViewModel
                {
                    CalendarWeek = DaysOfWeek,
                    CurrentMonth = month,
                    CurrentYear = year,
                    CurrentDay = day,
                    Months = Constants.Months,
                    TimeSheets = timeSheets,
                    Clients = clients,
                    Projects = projects,
                    Categories = categories,
                    DayTotalTime = dayTotalTime,
                    ProjectCategories = projectCategories,
                    WeekNumber = CultureInfo.CurrentCulture.Calendar.GetWeekOfYear(currentDate, CalendarWeekRule.FirstDay, DayOfWeek.Sunday)
                };
                return View(timeSheetsDetailViewModel);
            }
            catch (BusinessException ex)
            {
                throw;
            }
        }

        [Error]
        public ActionResult Create(int year, int month, int day)
        {
            try
            {
                int categoryId;
                int projectId;
                int clientId;
                decimal time;
                decimal overtime;
                int projectCategoryId = -1;

                string[] clients = Request.Form.GetValues("clientId");
                string[] projects = Request.Form.GetValues("projectId");
                string[] categories = Request.Form.GetValues("categoryId");
                string[] descriptions = Request.Form.GetValues("description");
                string[] times = Request.Form.GetValues("time");
                string[] overtimes = Request.Form.GetValues("overtime");

                var teamMember = this.teamMemberManager.GetAll().FirstOrDefault();

                for (int i = 0; i < clients.Count(); i++)
                {
                    if (!int.TryParse(categories[i], out categoryId))
                    {
                        continue;
                    }
                    if (!int.TryParse(projects[i], out projectId))
                    {
                        continue;
                    }
                    if (!int.TryParse(clients[i], out clientId))
                    {
                        continue;
                    }
                    if (!decimal.TryParse(times[i], out time))
                    {
                        continue;
                    }
                    if (overtimes[i] == "")
                    {
                        overtime = 0;
                    }
                    else if (!decimal.TryParse(overtimes[i], out overtime))
                    {
                        continue;
                    }

                    if (this.projectCategoryRepository.GetAll().Where(pc => pc.CategoryId == categoryId && pc.ProjectId == projectId).Count() > 0)
                    {
                        projectCategoryId = this.projectCategoryRepository.GetAll().Where(pc => pc.CategoryId == categoryId && pc.ProjectId == projectId).First().Id;
                    }
                    else
                    {
                        ProjectCategory newProjectCategory = new ProjectCategory()
                        {
                            CategoryId = categoryId,
                            ProjectId = projectId
                        };
                        this.projectCategoryRepository.Add(newProjectCategory);
                    }

                    if (projectCategoryId != -1)
                    {
                        DAL.Contracts.Entities.TimeSheet newTimeSheet = new DAL.Contracts.Entities.TimeSheet()
                        {
                            ClientId = clientId,
                            Description = descriptions[i],
                            Time = time,
                            Overtime = overtime,
                            Date = new DateTime(year, month, day),
                            TeamMemberId = teamMember.Id,
                            ProjectCategoryId = projectCategoryId
                        };
                        this.timeSheetManager.Create(newTimeSheet);
                    }
                    else
                    {
                        DAL.Contracts.Entities.TimeSheet newTimeSheet = new DAL.Contracts.Entities.TimeSheet()
                        {
                            ClientId = clientId,
                            Description = descriptions[i],
                            Time = time,
                            Overtime = overtime,
                            Date = new DateTime(year, month, day),
                            TeamMemberId = teamMember.Id,
                            ProjectCategoryId = projectCategoryRepository.GetAll().LastOrDefault().Id
                        };
                        this.timeSheetManager.Create(newTimeSheet);
                    }
                }
            }
            catch (BusinessException ex)
            {
                throw;
            }

            return RedirectToAction("Index", new { year = year, month = month, day = day });
        }

        [Error]
        public void DaysAfter(int year, int month, int day, int dayOffset, ref List<Tuple<int, int, int, string, string>> daysOfWeek)
        {
            int startDay = 0;
            for (int i = day + 1; i <= day + dayOffset; i++)
            {

VegaIT.TimeSheet.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

VegaIT.TimeSheet.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

VegaIT.TimeSheet.Web/Views/Home/Index.cshtml
@model VegaIT.TimeSheet.Web.Models.TimeSheetsViewModel

@{
    ViewBag.Title = "TimeSheet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
            <h2><i class="ico timesheet"></i>TimeSheet</h2>
            <div class="grey-box-wrap">
                <div class="top">
                    @if (Model.CurrentMonth == 1)
                    {
                        <a href="@Url.Action("Index", "Home", new { month = 12, year = Model.CurrentYear-1 }, null)" class="prev"><i></i>previous month</a>
                    }
                    else
                    {
                        <a href="@Url.Action("Index", "Home", new { month = Model.CurrentMonth - 1, year = Model.CurrentYear }, null)" class="prev"><i></i>previous month</a>
                    }
                    
                    <span class="center">@Model.Months[Model.CurrentMonth], @Model.CurrentYear</span>
                    
                    @if (Model.CurrentMonth == 12 )
                    {
                        <a href="@Url.Action("Index", "Home", new { month = 1, year = Model.CurrentYear + 1 }, null)" class="next"><i></i>next month</a>
                    }
                    else
                    {
                        <a href="@Url.Action("Index", "Home", new { month = Model.CurrentMonth + 1, year = Model.CurrentYear }, null)" class="next">next month<i></i></a>
                    }
                </div>
                <div class="bottom">

                </div>
            </div>
            <table class="month-table">
                <tr class="head">
                    <th><span>monday</span></th>
                    <th>tuesday</th>
                    <th>wednesday</th>
                    <th>thursday</th>
                    <th>friday</th>
                    <th>saturday</th>
                    <th>sunday</th>
                </tr>
                <tr class="mobile-head">
                    <th>mon</th>
                    <th>tue</th>
                    <th>wed</th>
                    <th>thu</th>
                    <th>fri</th>
                    <th>sat</th>
                    <th>sun</th>
                </tr>
                @for (int i = 0; i < Model.CalendarMonth.Count / 7; i++)
                {
                    <tr>
                        @for (int j = i*7; j < i*7+7; j++)
                        {
                            <td class="@Model.CalendarMonth[j].Item5">
                                <div class="date">
                                    <span>@Model.CalendarMonth[j].Item3.</span>
                                </div>
                                <div class="hours">
                                    <a href="@Url.Action("Index", "TimeSheets", new { month = @Model.CalendarMonth[j].Item2, year = @Model.CalendarMonth[j].Item1, day = @Model.CalendarMonth[j].Item3 }, null)">
                                        Hours: <span>@Model.CalendarMonth[j].Item4</span>
                                    </a>
                                </div>
                            </td>
                        }
                    </tr>
                }
            </table>
            <div class="total">
                <span>Total hours: <em>@Model.TotalTime</em></span>
            </div>