VegaIT.TimeSheet.Web/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VegaIT.TimeSheet.Web.Helpers;

namespace VegaIT.TimeSheet.Web.Controllers
{
    [Error]
    public class CategoriesController : Controller
    {
        [Error]
        // GET: Categories
        public ActionResult Index()
        {
            return PartialView();
        }
    }
}

VegaIT.TimeSheet.Web/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using VegaIT.TimeSheet.Business.Contracts;
using VegaIT.TimeSheet.Business.Contracts.Exceptions;
using VegaIT.TimeSheet.Common;
using VegaIT.TimeSheet.DAL.Contracts.Entities;
using VegaIT.TimeSheet.Web.Helpers;
using VegaIT.TimeSheet.Web.Models;

namespace VegaIT.TimeSheet.Web.Controllers
{
    [Error]
    public class ClientsController : Controller
    {
        private readonly IClientManager clientManager;
        private readonly ICountryManager countryManager;

        public ClientsController(IClientManager clientManager, ICountryManager countryManager)
        {
            this.clientManager = clientManager;
            this.countryManager = countryManager;
        }

        [Error]
        // GET: Clients
        public ActionResult Index(int pageNumber = 1, string firstLetter = "", string searchText = "")
        {
            try
            {
                var existingClients = this.clientManager.GetAll().Select(c => c.Name.ElementAt(0)).ToList();

                IEnumerable<Client> clients = this.clientManager.GetBy(pageNumber, firstLetter, searchText);

                List<Tuple<char, string>> letters = new List<Tuple<char, string>>();

                foreach (char letter in Constants.Letters)
                {
                    if (letter.ToString().Equals(firstLetter))
                        letters.Add(Tuple.Create(letter, Constants.Active));
                    else if (existingClients.Contains(letter))
                        letters.Add(Tuple.Create(letter, string.Empty));
                    else
                        letters.Add(Tuple.Create(letter, Constants.Disabled));
                }

                ClientsViewModel clientsViewModel = new ClientsViewModel
                {
                    Clients = clients,
                    Countries = this.countryManager.GetAll(),
                    Letters = letters,
                    Pages = clients.Count() / Constants.PageSize + 1,
                    Letter = firstLetter,
                    SearchText = searchText
                };
                return View(clientsViewModel);
            }
            catch (BusinessException ex)
            {
                throw;
            }
        }

        [Error]
        public ActionResult Create(string name, string address, string city, string zipCode, int countryId)
        {
            try
            {
                Client newClient = new Client()
                {
                    Name = name,
                    Address = address,
                    City = city,
                    ZipCode = zipCode,
                    CountryId = countryId
                };
                this.clientManager.Create(newClient);
            }
            catch (BusinessException ex)
            {
                throw;
            }
            return RedirectToAction("Index");
        }

        [Error]
        public ActionResult Update(int id, string name, string address, string city, string zipCode, int countryId)
        {
            try
            {
                Client clientToUpdate = new Client()
                {
                    Id = id,
                    Name = name,
                    Address = address,
                    City = city,
                    ZipCode = zipCode,
                    CountryId = countryId
                };
                this.clientManager.Update(clientToUpdate);
            }
            catch (BusinessException ex)
            {
                throw;
            }
            return RedirectToAction("Index");
        }

        [Error]
        public ActionResult Delete(int id)
        {
            try
            {
                this.clientManager.Delete(id);
            }
            catch (BusinessException ex)
            {
                throw;
            }
            return RedirectToAction("Index");
        }
    }
}

VegaIT.TimeSheet.Web/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VegaIT.TimeSheet.Business;
using VegaIT.TimeSheet.Business.Contracts;
using VegaIT.TimeSheet.Business.Contracts.Exceptions;
using VegaIT.TimeSheet.Common;
using VegaIT.TimeSheet.DAL;
using VegaIT.TimeSheet.DAL.Contracts.Entities;
using VegaIT.TimeSheet.Web.Helpers;
using VegaIT.TimeSheet.Web.Models;

namespace VegaIT.TimeSheet.Web.Controllers
{
    [Error]
    public class ProjectsController : Controller
    {
        private readonly IProjectManager projectManager;
        private readonly IClientManager clientManager;
        private readonly ITeamMemberManager teamMemberManager;

        public ProjectsController(IClientManager clientManager, IProjectManager projectManager, ITeamMemberManager teamMemberManager)
        {
            this.clientManager = clientManager;
            this.projectManager = projectManager;
            this.teamMemberManager = teamMemberManager;
        }

        [Error]
        // GET: Projects
        public ActionResult Index(int pageNumber = 1, string firstLetter = "", string searchText = "")
        {
            try
            {
                var existingProjects = this.projectManager.GetAll().Select(p => p.Name.ElementAt(0)).ToList();

                IEnumerable<Project> projects = this.projectManager.GetBy(pageNumber, firstLetter, searchText);

                List<Tuple<char, string>> letters = new List<Tuple<char, string>>();

                foreach (char letter in Constants.Letters)
                {
                    if (letter.ToString().Equals(firstLetter))
                        letters.Add(Tuple.Create(letter, Constants.Active));
                    else if (existingProjects.Contains(letter))
                        letters.Add(Tuple.Create(letter, string.Empty));
                    else
                        letters.Add(Tuple.Create(letter, Constants.Disabled));
                }

                ProjectsViewModel projectsViewModel = new ProjectsViewModel
                {
                    Projects = projects,
                    Clients = this.clientManager.GetAll(),
                    TeamMembers = this.teamMemberManager.GetAll(),
                    Letters = letters,
                    Pages = projects.Count() / Constants.PageSize + 1,
                    Letter = firstLetter,
                    SearchText = searchText
                };
                return View(projectsViewModel);
            }
            catch (BusinessException ex)
            {
                throw;
            }
        }

        [Error]
        public ActionResult Create(string name, string description, int leadId, int clientId)
        {
            try
            {
                Project newProject = new Project()
                {
                    Name = name,
                    Description = description,
                    Status = 1,
                    LeadId = leadId,
                    ClientId = clientId
                };
                this.projectManager.Create(newProject);
            }
            catch (BusinessException ex)
            {
                throw;
            }
            return RedirectToAction("Index");
        }

        [Error]
        public ActionResult Update(int id, string name, string description, int status, int leadId, int clientId)
        {
            try
            {
                Project projectToUpdate = new Project()
                {
                    Id = id,
                    Name = name,
                    Description = description,
                    Status = status,
                    LeadId = leadId,
                    ClientId = clientId
                };
                this.projectManager.Update(projectToUpdate);
            }
            catch (BusinessException ex)
            {
                throw;
            }
            return RedirectToAction("Index");
        }

        [Error]
        public ActionResult Delete(int id)
        {
            try
            {
                this.projectManager.Delete(id);
            }
            catch (BusinessException ex)
            {
                throw;
            }
            return RedirectToAction("Index");
        }
    }
}

VegaIT.TimeSheet.Web/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using VegaIT.TimeSheet.Business.Contracts;
using VegaIT.TimeSheet.Business.Contracts.Exceptions;
using VegaIT.TimeSheet.DAL.Contracts.Repositories;
using VegaIT.TimeSheet.Web.Helpers;
using VegaIT.TimeSheet.Web.Models;

namespace VegaIT.TimeSheet.Web.Controllers
{
    [Error]
    public class ReportsController : Controller
    {
        private readonly ITimeSheetManager timeSheetManager;
        private readonly ITeamMemberManager teamMemberManager;
        private readonly IClientManager clientManager;
        private readonly IProjectManager projectManager;
        private readonly ICategoryRepository categoryRepository;

        public ReportsController(ITimeSheetManager timeSheetManager, IClientManager clientManager, IProjectManager projectManager,
                                    ICategoryRepository categoryRepository, ITeamMemberManager teamMemberManager)
        {
            this.timeSheetManager = timeSheetManager;
            this.clientManager = clientManager;
            this.projectManager = projectManager;
            this.categoryRepository = categoryRepository;
            this.teamMemberManager = teamMemberManager;
        }

        [Error]
        // GET: Reports
        public ActionResult Index(int teamMemberId = 0, int clientId = 0, int projectId = 0, int categoryId = 0, DateTime? startDate = null, DateTime? endDate = null)
        {
            try
            {
                List<Tuple<DateTime, string, string, string, string, decimal>> reportResults = new List<Tuple<DateTime, string, string, string, string, decimal>>();
                decimal reportTotalTime = 0;

                var teamMembers = this.teamMemberManager.GetAll();
                var clients = this.clientManager.GetAll();
                var projects = this.projectManager.GetAll();
                var categories = this.categoryRepository.GetAll();

                IEnumerable<DAL.Contracts.Entities.TimeSheet> resultingTimeSheets = new List<DAL.Contracts.Entities.TimeSheet>();
                if (startDate.HasValue && endDate.HasValue)
                {
                    resultingTimeSheets = this.timeSheetManager.GetBy(teamMemberId, clientId, projectId, categoryId, startDate.Value, endDate.Value);
                }

                foreach (DAL.Contracts.Entities.TimeSheet timeSheet in resultingTimeSheets)
                {
                    reportResults.Add(new Tuple<DateTime, string, string, string, string, decimal>(timeSheet.Date,
                                        teamMembers.Where(tm => tm.Id == teamMemberId).FirstOrDefault().Name,
                                        projects.Where(p => p.Id == projectId).FirstOrDefault().Name,
                                        categories.Where(c => c.Id == categoryId).FirstOrDefault().Name,
                                        timeSheet.Description, timeSheet.Time));
                    reportTotalTime += timeSheet.Time;
                }

                ReportsViewModel reportsViewModel = new ReportsViewModel
                {
                    TeamMembers = teamMembers,
                    Clients = clients,
                    Projects = projects,
                    Categories = categories,
                    ResultTimeSheets = reportResults,
                    TotalTime = reportTotalTime
                };
                return View(reportsViewModel);
            }
            catch (BusinessException ex)
            {
                throw;
            }
        }
    }
}

VegaIT.TimeSheet.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js ie6"> <![endif]-->
<!--[if IE 7]>         <html class="no-js ie7"> <![endif]-->
<!--[if IE 8]>         <html class="no-js ie8"> <![endif]-->
<!--[if gt IE 8]><!--><html class="no-js"><!--<![endif]-->
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
    <meta name="viewport" content="target-densitydpi=device-dpi">
    <meta name="viewport" content="width=device-width, initial-scale = 1.0, maximum-scale = 1.0" />

    <title>TimeSheet</title>
    <meta name="description" content="" />

    <link rel="stylesheet" href="~/Content/assets/css/style.css">
    <script type="text/javascript" src="~/Scripts/main/modernizr-2.6.2.min.js"></script>

    @Styles.Render("~/Content/assets/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="container">
        <header>
            <div class="top-bar"></div>
            <div class="wrapper">
                <a href="@Url.Action("Index","Home")" class="logo">
                    <img src="~/Content/assets/images/logo.png" alt="VegaITSourcing Timesheet" />
                </a>
                <ul class="user right">
                    <li>
                        <a href="javascript:;">Sladjana Miljanovic</a>
                        <div class="invisible"></div>
                        <div class="user-menu">
                            <ul>
                                <li>
                                    <a href="javascript:;" class="link">Change password</a>
                                </li>
                                <li>
                                    <a href="javascript:;" class="link">Settings</a>
                                </li>
                                <li>
                                    <a href="javascript:;" class="link">Export all data</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="last">
                        <a href="javascript:;">Logout</a>
                    </li>
                </ul>
                <nav>
                    <ul class="menu" id="menu">
                        <li>
                            <a href="@Url.Action("Index","Home")" class="btn nav active" id="TimeSheetLink" onclick="buttonClicked(this.id);">TimeSheet</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","Clients")" class="btn nav" id="ClientsLink" onclick="buttonClicked(this.id);">Clients</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","Projects")" class="btn nav" id="ProjectsLink" onclick="buttonClicked(this.id);">Projects</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","Categories")" class="btn nav" id="CategoriesLink" onclick="buttonClicked(this.id);">Categories</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","TeamMembers")" class="btn nav" id="TeamMembersLink" onclick="buttonClicked(this.id);">Team members</a>
                        </li>
                        <li class="last">
                            <a href="@Url.Action("Index","Reports")" class="btn nav" id="ReportsLink" onclick="buttonClicked(this.id);">Reports</a>
                        </li>
                    </ul>
                    <div class="mobile-menu">
                        <a href="javascript:;" class="menu-btn">
                            <span>mobile menu</span>
                        </a>
                        <ul>
                            <li>
                                <a href="javascript:;">TimeSheet</a>
                            </li>
                            <li>
                                <a href="javascript:;">Clients</a>
                            </li>
                            <li>
                                <a href="javascript:;">Projects</a>
                            </li>
                            <li>
                                <a href="javascript:;">Categories</a>
                            </li>
                            <li>
                                <a href="javascript:;">Team members</a>
                            </li>
                            <li class="last">
                                <a href="javascript:;">Reports</a>
                            </li>
                        </ul>
                    </div>
                    <span class="line"></span>
                </nav>
            </div>
        </header>
        <div class="container body-content">
            <div class="wrapper">
                <section class="content">
                    @RenderBody()
                </section>
            </div>
            <hr />
            <footer>
                <div class="wrapper">
                    <ul>
                        <li>
                            <span>Copyright 2013. VegaITSourcing All rights reserved</span>
                        </li>
                    </ul>
                    <ul class="right">
                        <li>
                            <a href="javascript:;">Terms of service</a>
                        </li>
                        <li>
                            <a href="javascript:;" class="last">Privacy policy</a>
                        </li>
                    </ul>
                </div>
            </footer>
        </div>
    </div>

    <!-- javascript -->
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">window.jQuery || document.write("<script src='~/Scripts/main/jquery-1.8.3.min.js'>\x3C/script>")</script>
    <script type="text/javascript" src="~/Scripts/main/default.js"></script>
    <script type="text/javascript" src="~/Scripts/main/accordion.js"></script>
    <script type="text/javascript" src="~/Scripts/libs/jquery.fancybox.js"></script>
    <script type="text/javascript" src="~/Scripts/libs/jquery-ui-1.9.2.custom.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery-1.10.2.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.unobtrusive-ajax.js"></script>

    <script type="text/javascript">
        function buttonClicked(clicked_id)
        {
            var elem = document.getElementById(clicked_id);
            var list = document.getElementById("menu").getElementsByTagName("li");
            for (i = 0; i < list.length; i++)
            {
                if (list[i].id != elem.id)
                {
                    list[i].getElementByTagName("a").className = "btn nav";
                }
            }
            elem.className = "btn nav active";
        }
    </script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>